from torch import Tensor
from typing import List

def three_nn(unknowns: Tensor, knows: Tensor) -> List[Tensor]: ...
def three_interpolate(points: Tensor, idx: Tensor, weight: Tensor) -> Tensor: ...
def three_interpolate_grad(grad_out: Tensor, idx: Tensor, weight: Tensor, m: int) -> Tensor: ...
