from torch import Tensor

def gather_points(points: Tensor, idx: Tensor) -> Tensor: ...
def gather_points_grad(grad_out: Tensor, idx: Tensor, n: int) -> Tensor: ...
def furthest_point_sampling(points: Tensor, nsamples: int) -> Tensor: ...