from typing import TYPE_CHECKING

import tkinter as tk
import threading
import time
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

from apps.common.loops.onlineReader import OnlineReaderLoop
from apps.common.pcd.pointCloud import SimplePointCloud5D
from apps.common.pcd.pointCloudVis import PointCloudFigureFrame
from kinect_toolkits.kinectData import Skeleton
from kinect_toolkits.kinectVis import SkeletonFigureFrame


if TYPE_CHECKING:
    from dl_engine.runner.inference_engine import InferenceEngine
    from apps.online_skeleton_estim.runner import OnlineSkeletonEstimationRunner



class OnlineReaderPredictLoop(OnlineReaderLoop):
    def __init__(self, 
                 reader, 
                 interval: float, 
                 inference_engine: 'InferenceEngine',
                 visualize: bool = False, 
                 figure_cfg: dict = None):
        super().__init__(reader, interval)
        self.visualize = visualize
        self.inference_engine = inference_engine
        self.figure_cfg = figure_cfg or {'figsize': (5, 5), 'dpi': 100}
        self.gui_initialized = False
        if self.visualize:
            self._init_gui()

    def _init_gui(self):
        print("Initializing GUI...")
        self.root = tk.Tk()
        self.root.title("Skeleton Visualization")
        self.figure_frame = SkeletonFigureFrame(master=self.root, figure_cfg=self.figure_cfg)
        self.figure_frame.pack(fill=tk.BOTH, expand=True)
        self.gui_initialized = True

    def _process_data(self, data):
        """
        Process the data generated by the reader.
        If visualization is enabled, update the point cloud frame.
        
        Args:
            data (tuple): Expected to be (data_ok, frame_number, det_obj),
                          where det_obj is an iterable of SimplePoint3D objects.
        """
        data_ok, frame_number, det_obj = data
        if data_ok:
            try:
                point_cloud = SimplePointCloud5D.from_dict(det_obj)
                inference_output = self.inference_engine.infer(point_cloud)
                skeleton_value_list = inference_output['tensor'][0, -1, :].tolist()
                skeleton = Skeleton.from_sequence(skeleton_value_list, 
                                                used_points=self.inference_engine.keypoints_involved,
                                                order='xzy')
                if self.visualize and self.gui_initialized:
                    self.root.after(0, self.figure_frame.update,skeleton)
            except RuntimeError as e:
                print(e)
            return data

    def _after_stop_hook(self):
        """Close the data port and destroy the GUI if open."""
        super()._after_stop_hook()
        if self._reader.Data_port.is_open:
            self._reader.Data_port.close()
        if self.visualize and self.gui_initialized:
            self.root.after(0, self.root.quit)

    @classmethod
    def from_dict(cls, cfg):
        return cls(
            reader=cfg.get("reader"),
            interval=cfg.get("interval"),
            visualize=cfg.get("visualize", False),
            figure_cfg=cfg.get("figure_cfg", None),
            inference_engine=cfg.get("inference_engine")
        )