tracker_cfg = dict(
    type="GTrackKTracker",
    keep_radial=False,
    do_dev2standard = False,
    tracker_params=dict(
        FB_FRAMES_BATCH=1,
        FB_FRAMES_BATCH_STATIC=1,
        DB_POINTS_THRES=40,
        DB_SPREAD_THRES=0.7,
        DB_EPS=0.3,
        DB_RANGE_WEIGHT=0.03,
        DB_Z_WEIGHT=0.4,
        DB_MIN_SAMPLES_MIN=35,
        KF_R_STD=0.1,
        KF_P_INIT=0.1,
        KF_GROUP_DISP_EST_INIT=0.1,
        KF_ENABLE_EST=False,
        KF_A_N=0.9,
        KF_EST_POINTNUM=30,
        KF_SPREAD_LIM=[0.2, 0.2, 2, 1.2, 1.2, 0.2],
        KF_A_SPR=0.9,
        KF_Q_STD=1.0,
        TR_LIFETIME_DYNAMIC=3,
        TR_LIFETIME_STATIC=7,
        TR_GATE=4.5,
        TR_MAX_TRACKS=4,
        TR_VEL_THRES=0.12,
        NUM_DYNAMIC_POINTS_THRESHOLD=3,
        DOPPLER_THRESHOLD=0,
        MIN_VELOCITY_STOP_NO_DYNAMIC_POINTS=0.04,
        MIN_VELOCITY_STOP_NO_POINTS=0.04,
        MIN_VELOCITY_SLOW_DOWN=1,
        ENABLE_TORSO_TRACKING = False, 
        MAX_LIMB_VELOCITY = 1.0,    # m/s
        MIN_TORSO_MOVEMENT = 0.1 ,      # meters
        TORSO_DENSITY_RADIUS = 0.3,    # meters
        MIN_TORSO_POINTS = 8
    )
)