tracker_cfg = dict(
    keep_radial = True,
    do_dev2standard = False,
    result_in_polar = False,
    type = "RKFTracker",
    tracker_params = dict(
        KF_R_STD=0.1,
        KF_Q_STD=1,
        KF_P_INIT=0.1,
        KF_GROUP_DISP_EST_INIT=0.1,
        KF_ENABLE_EST=False,
        KF_A_N=0.9,
        KF_EST_POINTNUM=10,
        KF_SPREAD_LIM=[0.2, 0.2, 2, 1.2, 1.2, 0.2],
        KF_A_SPR=0.9,
        DB_POINTS_THRES=20,
        DB_SPREAD_THRES=0.7,
        DB_EPS=0.3,
        DB_RANGE_WEIGHT=0.03,
        DB_Z_WEIGHT=0.1,
        DB_MIN_SAMPLES_MIN=40,
        FB_FRAMES_BATCH_STATIC=2,
        FB_FRAMES_BATCH=2,
        TR_LIFETIME_DYNAMIC=3,
        TR_LIFETIME_STATIC=7,
        TR_GATE=0.4,
        TR_MAX_TRACKS=1,
        TR_VEL_THRES = 0.12,
        ENABLE_OUTLIER_TREATMENT=True,
        ENABLE_TORSO_TRACKING = False,  # New flag
        MAX_LIMB_VELOCITY = 1.0,    # m/s
        MIN_TORSO_MOVEMENT = 0.1 ,      # meters
        TORSO_DENSITY_RADIUS = 0.3,    # meters
        MIN_TORSO_POINTS = 8
    )
)