from apps.common.loops.onlineReader import OnlineReaderLoop


import tkinter as tk
import threading
import time
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

from apps.common.pcd.pointCloud import SimplePointCloud5D
from apps.common.pcd.pointCloudVis import PointCloudFigureFrame

# Assuming these classes exist from your earlier code:
# - PointCloudFigure and PointCloudFigureFrame
# - OnlineReaderLoop and BaseRadarProcessLoop
# - BaseBufferedReader, SimplePoint3D, etc.

class CustomReaderLoop(OnlineReaderLoop):
    def __init__(self, reader, interval: float, visualize: bool = False, figure_cfg: dict = None):
        """
        CustomReaderLoop initializes its own Tkinter GUI components if visualization is enabled.
        
        Args:
            reader (BaseBufferedReader): The reader object (should be pre-built).
            interval (float): Interval between data updates.
            visualize (bool): Whether to initialize and update the point cloud GUI.
            figure_cfg (dict): Configuration for the matplotlib figure (optional).
        """
        super().__init__(reader, interval)
        self.visualize = visualize
        self.figure_cfg = figure_cfg or {'figsize': (5, 5), 'dpi': 100}
        self.gui_initialized = False
        if self.visualize:
            self._init_gui()

    def _init_gui(self):
        """Initializes the Tkinter root and point cloud figure frame."""
        print("Initializing GUI...")
        self.root = tk.Tk()
        self.root.title("Point Cloud Visualization")
        self.figure_frame = PointCloudFigureFrame(self.root, self.figure_cfg)
        self.figure_frame.pack(fill=tk.BOTH, expand=True)
        self.gui_initialized = True

    def _process_data(self, data):
        """
        Process the data generated by the reader.
        If visualization is enabled, update the point cloud frame.
        
        Args:
            data (tuple): Expected to be (data_ok, frame_number, det_obj),
                          where det_obj is an iterable of SimplePoint3D objects.
        """
        data_ok, frame_number, det_obj = data
        if data_ok:
            print(f"Num Objects Detected: {det_obj['numObj']}")

        if data_ok and self.visualize and self.gui_initialized:
            # Update the point cloud visualization.
            self.root.after(0, self.figure_frame.update, SimplePointCloud5D.from_dict(det_obj).points)
        return data

    def _after_stop_hook(self):
        """Close the data port and destroy the GUI if open."""
        super()._after_stop_hook()
        if self._reader.Data_port.is_open:
            self._reader.Data_port.close()
        if self.visualize and self.gui_initialized:
            self.root.after(0, self.root.quit)

    @classmethod
    def from_dict(cls, cfg):
        return cls(
            reader=cfg.get("reader"),
            interval=cfg.get("interval"),
            visualize=cfg.get("visualize", False),
            figure_cfg=cfg.get("figure_cfg", None)
        )